import { StyleSheet } from 'react-native';
import { assignNestedObj } from '../../../../../../util/object';
import brandStyles from './brand';

const styles = StyleSheet.create({
	container: {},
	titleContainer: {},
	titleWrapper: {},
	title: {},
	stepperContainer: {},
	webView: {},
	fromWrapper: {},
	fromButton: {},
	fromLoading: {},
	stepperWrapper: {},
	stepperCheckout: {},
	stepperButton: {},
	stepperButtonContent: {},
	stepperButtonText: {},
	seeCalculationButton: {},
	amountButton: {},
	selectedAmountButton: {},
	amountWrapper: {},
	amountContent: {},
	amountTextInput: {},
	amountButton2: {},
	fromText: {},
	receiveWrapper: {},
	receiveContent: {},
	receiveText: {},
	receiveButton: {},
	receiveRightContent: {},
	icon: {},
	currencyText: {},
	sRow: {},
	sMark: {},
	mRow: {},
	mMark: {},
	markIcon: {},
	markText: {},
	markTitleText: {},
	modalContainer: {},
	modalWrapper: {},
	modalScrollView: {},
	modalItemContainer: {},
	modalItemIcon: {},
	dropdownButton: {},
	dropdownIcon: {},
	menuButton: {},
	menuIcon: {},
	menuContent: {},
	menuItem: {},
	menuItemBorderBottom: {},
	menuItemLeftIcon: {},
	menuItemTitle: {},
	menuItemRightIcon: {},
	tokenText: {},
	networkWrapper: {},
	networkTitle: {},
	buttonText: {},
	confirmTopWrapper: {},
	confirmSectionTitle: {},
	confirmTopNameWrapper: {},
	confirmNameMarker: {},
	confirmTokenName: {},
	addressWrapper: {},
	addressScroll: {},
	address: {},
	dasher: {},
	addressIcon: {},
	confirmContentItemWrapper: {},
	confirmContentLeft: {},
	confirmContentRight: {},
	confirmTotalLeft: {},
	confirmTotalRight: {},
	collapsibleWrapper: {},
	collapsible: {}
});

export default assignNestedObj(styles, brandStyles);
